fix(main-collection, collection-card): add liquid
rieznikk/liquid-course pull request #2
Opened 2022-07-31 19:03 UTC by rieznikk

1. Wrote settings for block
2. Delete trash from section.settings
3. Move mockup to snippet (collection-card)
4. Used in loop render
😁😁😁

2022-07-31 19:05 UTC, rieznikk commented
https://rieznik-dev.myshopify.com/ (password: admin)

2022-07-31 21:12 UTC, AncleMarvel requested changes
Пока не исправишь, не закрывай PR

2022-07-31 21:12 UTC, AncleMarvel commented on snippets/collection-card.liquid
> +        <img src="{{ block.settings.photo }}" class="collection-card_photo">
Ты ж передал в переменную photo значение block.settings.photo, почему ты тут не используешь переменную?

2022-07-31 21:12 UTC, AncleMarvel commented on snippets/collection-card.liquid
> +    <h2 class="heading alex-murphy__80-50_400">{{ block.settings.heading }}</h2>
Где использование переменной, которую ты передал в снипет?

2022-07-31 21:12 UTC, AncleMarvel commented on snippets/collection-card.liquid
> +            <p class="red-hat__15-20_400">{{ block.settings.description }}</p>
Где использование переменной, которую ты передал в снипет?

2022-07-31 21:12 UTC, AncleMarvel commented on snippets/collection-card.liquid
> +            <a class="chakra-petch__20-25_700 collection-card_btn" href="{{ block.settings.link_text }}">{{ block.settings.btn_text }}</a>
Где использование переменной, которую ты передал в снипет?

2022-07-31 21:12 UTC, AncleMarvel commented on sections/main-collection.liquid
> +            btn_text: block.settings.btn_text
зачем ты рендеришь сниппет вне секции?

2022-07-31 21:12 UTC, AncleMarvel commented on sections/main-collection.liquid
> +                    <div class="collection-card">
Ты должен был заменить эту разметку на рендер снипета

2022-07-31 21:12 UTC, AncleMarvel commented on sections/main-collection.liquid
> +        <div class="collection-card_wrapper">
Это не обёртка карточки, 
то должен быть контейнер для карточек

2022-08-01 10:10 UTC, AncleMarvel requested changes

2022-08-01 10:10 UTC, AncleMarvel commented on sections/main-collection.liquid
> +                        heading: block.settings.heading,
Забыл про description

2022-08-01 10:10 UTC, AncleMarvel commented on sections/main-collection.liquid
> +                        <!-- <div class="collection-card">
Remove this comment

2022-08-01 10:10 UTC, AncleMarvel commented on sections/main-collection.liquid
> +        </div> -->
Remove all comments

2022-08-01 10:13 UTC, AncleMarvel commented on sections/main-collection.liquid
> +        <div class="collection-card_container">
Сначала два нижних подчеркивания, а потом 1, а у тебя сразу 1

2022-08-01 10:56 UTC, AncleMarvel commented
Если у нас в блоке выбрана коллекция, тогда берём данные из неё, если нет, то как и до этого. Ниже реализация. Если есть вопросы - в тг. 

1. Добавить блоку возможность выбрать коллекцию.
2. В условной конструкции "если блок == коллекшн_кард" добавить следующее условие:
**ЕСЛИ** блок.настройки.коллекция != blank (это значит, если в кастомайзе выбрана коллекция, blank - пустой, то есть если не пустой) **ТОГДА** на каждое поле данных создать переменную а данные для неё будут браться не из block.settings, а из объекта коллекции. Создавать переменные с помощью assign. 
Например: assign heading = block.settings.collection.title, и так для всех своих данных.
**ИНАЧЕ**  данные будут браться не из коллекции, а как и до этого, то есть например block.settings.heading, тут тоже создаёшь переменные, типа: assign heading = block.settings.heading;
3. Созданные переменные передаёшь в сниппет. Если до этого ты писал в рендере heading: block.settings.heading, то теперь ты будешь в качестве значения передавать созданную переменную. Например heading: heading; Первый heading это переменная, которая будет использоваться в сниппете, второй - переменная, которую ты создал в условной конструкции.

2022-08-01 11:06 UTC, AncleMarvel commented
4. Для кнопок (ссылок): текст внутри кнопки общий для всех блоков, а значит это должна быть настройка секции, а не блока. В сниппет буш передавать link_text: section.settings.link_text;
5. Но вот URL у кнопок разный, и он берётся либо из объекта collection, либо из настройки блока block.settings.link_url;
То есть для урла всё таки надо создавать переменную: assign link_url = block.settings.collection.url ЛИБО block.settings.link_urk. Типа если есть коллекция, значит берём ссылку на неё, а если нету, то добавляем ссылку вручную через кастомайз

2022-08-01 11:22 UTC, merged